[build]
  base = "frontend"
  command = "pnpm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_URL = "https://zedideaarena-1.onrender.com/api"
