export const team = [
  {
    name: 'Sean Tinashe Nyakutira',
    role: 'Founder & CEO',
    bio: 'Lead developer and visionary behind ZedIdeaArena. Building the future of African innovation.',
    image: '/api/instagram-profile?username=mrseannyakutira',
    instagram: 'https://instagram.com/mrseannyakutira',
    website: 'https://mrseannyakutira.com',
    linkedin: '#',
    twitter: '#',
  },
  {
    name: 'Brendon Svotwa',
    role: 'Head of Operations',
    bio: 'Scaling the platform and managing day-to-day operations across Southern Africa.',
    image: '/placeholder-user.jpg',
    website: 'https://brendonsvotwa.vercel.app',
    linkedin: '#',
    twitter: '#',
  },
  {
    name: 'Chenai Chipato',
    role: 'Community Lead',
    bio: 'Growing the innovator network and building partnerships across the region.',
    image: '/placeholder-user.jpg',
    linkedin: '#',
    twitter: '#',
  },
  {
    name: 'Tyler B Picolani',
    role: 'Assistant Developer',
    bio: 'Building and maintaining platform features for a seamless experience.',
    image: '/placeholder-user.jpg',
    linkedin: '#',
    twitter: '#',
  },
  {
    name: 'Calvin Mupazviriwo',
    role: 'Marketing Director',
    bio: 'Driving growth and brand awareness across Southern Africa and beyond.',
    image: '/api/instagram-profile?username=ck_flames',
    instagram: 'https://instagram.com/ck_flames',
    linkedin: '#',
    twitter: '#',
  },
]
